version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 194722426612.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t my-container-app .
      - docker tag my-container-app:latest 194722426612.dkr.ecr.us-west-2.amazonaws.com/my-container-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 194722426612.dkr.ecr.us-west-2.amazonaws.com/my-container-app:latest
      - echo Writing image details...
      - printf '[{"name":"my-container-app","imageUri":"%s"}]' 194722426612.dkr.ecr.us-west-2.amazonaws.com/my-container-app:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
